//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameLogEscritorio.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameLogEscritorio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://localhost/gamelogapigrpc.
        /// </summary>
        internal static string ApiGrpcUrl {
            get {
                return ResourceManager.GetString("ApiGrpcUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://localhost/gamelogapi/gamelog/acceso.
        /// </summary>
        internal static string ApiUrlAcceso {
            get {
                return ResourceManager.GetString("ApiUrlAcceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://localhost/gamelogapi/gamelog.
        /// </summary>
        internal static string ApiUrlBase {
            get {
                return ResourceManager.GetString("ApiUrlBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://localhost/gamelogapi/gamelog/juego.
        /// </summary>
        internal static string ApiUrlJuego {
            get {
                return ResourceManager.GetString("ApiUrlJuego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://localhost/gamelogapi/gamelog/jugador.
        /// </summary>
        internal static string ApiUrlJugador {
            get {
                return ResourceManager.GetString("ApiUrlJugador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://localhost/gamelogapi/gamelog/like.
        /// </summary>
        internal static string ApiUrlLike {
            get {
                return ResourceManager.GetString("ApiUrlLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://localhost/gamelogapi/gamelog/login.
        /// </summary>
        internal static string ApiUrlLogin {
            get {
                return ResourceManager.GetString("ApiUrlLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://localhost/gamelogapi/gamelog/reporte.
        /// </summary>
        internal static string ApiUrlReporte {
            get {
                return ResourceManager.GetString("ApiUrlReporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://localhost/gamelogapi/gamelog/resena.
        /// </summary>
        internal static string ApiUrlResena {
            get {
                return ResourceManager.GetString("ApiUrlResena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://localhost/gamelogapi/gamelog/seguidor.
        /// </summary>
        internal static string ApiUrlSeguidor {
            get {
                return ResourceManager.GetString("ApiUrlSeguidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Argumentos para realizar la solicitud inválidos.
        /// </summary>
        internal static string ArgumentNullExcepcion {
            get {
                return ResourceManager.GetString("ArgumentNullExcepcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport.
        /// </summary>
        internal static string ConfiguracionCanalGRPC {
            get {
                return ResourceManager.GetString("ConfiguracionCanalGRPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El juego a buscar no se encuentra registrado..
        /// </summary>
        internal static string ErrorAlBuscarJuego {
            get {
                return ResourceManager.GetString("ErrorAlBuscarJuego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error inesperado al querer realizar la solicitud.
        /// </summary>
        internal static string Excepcion {
            get {
                return ResourceManager.GetString("Excepcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la conexión de red o al intentar realizar la solicitud con el servidor.
        /// </summary>
        internal static string HttpExcepcion {
            get {
                return ResourceManager.GetString("HttpExcepcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La imagen de perfil no fue encontrada..
        /// </summary>
        internal static string ImagenNoEncontrada {
            get {
                return ResourceManager.GetString("ImagenNoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al procesar la respuesta del Json.
        /// </summary>
        internal static string JsonExcepcion {
            get {
                return ResourceManager.GetString("JsonExcepcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El juego a buscar no se encuentra registrado..
        /// </summary>
        internal static string juegoIngresadoNoEncontrado {
            get {
                return ResourceManager.GetString("juegoIngresadoNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://api.rawg.io/api/games/.
        /// </summary>
        internal static string RawAPIGames {
            get {
                return ResourceManager.GetString("RawAPIGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 531c5bdb92ae41bd819b9901e3012568.
        /// </summary>
        internal static string RawgKey {
            get {
                return ResourceManager.GetString("RawgKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Juego no encontrado, quizá quisiste buscar: .
        /// </summary>
        internal static string RedireccionamientoSlug {
            get {
                return ResourceManager.GetString("RedireccionamientoSlug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /home/app/fotos/imagendeperfildefaultgamelog.png.
        /// </summary>
        internal static string RutaFotoPorDefecto {
            get {
                return ResourceManager.GetString("RutaFotoPorDefecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo de espera agotado..
        /// </summary>
        internal static string TaskCanceledExcepcion {
            get {
                return ResourceManager.GetString("TaskCanceledExcepcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador.
        /// </summary>
        internal static string tipoDeUsuarioPorDefecto {
            get {
                return ResourceManager.GetString("tipoDeUsuarioPorDefecto", resourceCulture);
            }
        }
    }
}
