//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameLogEscritorio.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameLogEscritorio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://localhost:443.
        /// </summary>
        public static string ApiGrpcUrl {
            get {
                return ResourceManager.GetString("ApiGrpcUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://localhost/gamelogapi/gamelog/acceso.
        /// </summary>
        public static string ApiUrlAcceso {
            get {
                return ResourceManager.GetString("ApiUrlAcceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://localhost/gamelogapi/gamelog.
        /// </summary>
        public static string ApiUrlBase {
            get {
                return ResourceManager.GetString("ApiUrlBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://localhost/gamelogapi/gamelog/juego.
        /// </summary>
        public static string ApiUrlJuego {
            get {
                return ResourceManager.GetString("ApiUrlJuego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://localhost/gamelogapi/gamelog/jugador.
        /// </summary>
        public static string ApiUrlJugador {
            get {
                return ResourceManager.GetString("ApiUrlJugador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://localhost/gamelogapi/gamelog/like.
        /// </summary>
        public static string ApiUrlLike {
            get {
                return ResourceManager.GetString("ApiUrlLike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://localhost/gamelogapi/gamelog/login.
        /// </summary>
        public static string ApiUrlLogin {
            get {
                return ResourceManager.GetString("ApiUrlLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://localhost/gamelogapi/gamelog/reporte.
        /// </summary>
        public static string ApiUrlReporte {
            get {
                return ResourceManager.GetString("ApiUrlReporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://localhost/gamelogapi/gamelog/resena.
        /// </summary>
        public static string ApiUrlResena {
            get {
                return ResourceManager.GetString("ApiUrlResena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://localhost/gamelogapi/gamelog/seguidor.
        /// </summary>
        public static string ApiUrlSeguidor {
            get {
                return ResourceManager.GetString("ApiUrlSeguidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo que desea ingresar no es una imagen.
        /// </summary>
        public static string ArchivoNoEsImagen {
            get {
                return ResourceManager.GetString("ArchivoNoEsImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Argumentos para realizar la solicitud inválidos.
        /// </summary>
        public static string ArgumentNullExcepcion {
            get {
                return ResourceManager.GetString("ArgumentNullExcepcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport.
        /// </summary>
        public static string ConfiguracionCanalGRPC {
            get {
                return ResourceManager.GetString("ConfiguracionCanalGRPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si desea realizar una modificación, por favor actualice uno de los campos mostrados.
        /// </summary>
        public static string EdicionSinCambios {
            get {
                return ResourceManager.GetString("EdicionSinCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El juego a buscar no se encuentra registrado..
        /// </summary>
        public static string ErrorAlBuscarJuego {
            get {
                return ResourceManager.GetString("ErrorAlBuscarJuego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error al querer leer la imagen a ingresar.
        /// </summary>
        public static string ErrorAlLeerImagen {
            get {
                return ResourceManager.GetString("ErrorAlLeerImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error inesperado al querer realizar la solicitud.
        /// </summary>
        public static string Excepcion {
            get {
                return ResourceManager.GetString("Excepcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los argumentos para realizar la solicitud no son los correctos, por favor verifique los datos que desea mandar..
        /// </summary>
        public static string GRPCArgumentosInvalidos {
            get {
                return ResourceManager.GetString("GRPCArgumentosInvalidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error al querer ejecutar la operación dentro del servidor multimedia.
        /// </summary>
        public static string GRPCErrorInterno {
            get {
                return ResourceManager.GetString("GRPCErrorInterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No cuenta con permisos para poder conectarse con el servidor multimedia. I.
        /// </summary>
        public static string GRPCPermisosInvalidos {
            get {
                return ResourceManager.GetString("GRPCPermisosInvalidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualmente no es posible comunicarse con el servidor para obtener archivos multimedia , inténtelo más tarde..
        /// </summary>
        public static string GRPCServidorNoDisponible {
            get {
                return ResourceManager.GetString("GRPCServidorNoDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La(s) foto(s) de perfil a obtener no han sido encontradas..
        /// </summary>
        public static string GRPElementosNoEncontrado {
            get {
                return ResourceManager.GetString("GRPElementosNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la conexión de red o al intentar realizar la solicitud con el servidor.
        /// </summary>
        public static string HttpExcepcion {
            get {
                return ResourceManager.GetString("HttpExcepcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La imagen de perfil no fue encontrada..
        /// </summary>
        public static string ImagenNoEncontrada {
            get {
                return ResourceManager.GetString("ImagenNoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al procesar la respuesta del Json.
        /// </summary>
        public static string JsonExcepcion {
            get {
                return ResourceManager.GetString("JsonExcepcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El juego a buscar no se encuentra registrado..
        /// </summary>
        public static string juegoIngresadoNoEncontrado {
            get {
                return ResourceManager.GetString("juegoIngresadoNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://api.rawg.io/api/games/.
        /// </summary>
        public static string RawAPIGames {
            get {
                return ResourceManager.GetString("RawAPIGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 531c5bdb92ae41bd819b9901e3012568.
        /// </summary>
        public static string RawgKey {
            get {
                return ResourceManager.GetString("RawgKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Juego no encontrado, quizá quisiste buscar: .
        /// </summary>
        public static string RedireccionamientoSlug {
            get {
                return ResourceManager.GetString("RedireccionamientoSlug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /home/app/fotos/imagendeperfildefaultgamelog.png.
        /// </summary>
        public static string RutaFotoPorDefecto {
            get {
                return ResourceManager.GetString("RutaFotoPorDefecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha podido localizar el servidor de archivos multimedia..
        /// </summary>
        public static string ServidorGRPCNoEncontrado {
            get {
                return ResourceManager.GetString("ServidorGRPCNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo de la imagen a ingresar debe ser menor a 2mb.
        /// </summary>
        public static string TamañoImagenMayor {
            get {
                return ResourceManager.GetString("TamañoImagenMayor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo de espera agotado..
        /// </summary>
        public static string TaskCanceledExcepcion {
            get {
                return ResourceManager.GetString("TaskCanceledExcepcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador.
        /// </summary>
        public static string tipoDeUsuarioPorDefecto {
            get {
                return ResourceManager.GetString("tipoDeUsuarioPorDefecto", resourceCulture);
            }
        }
    }
}
