//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GameLogEscritorio.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GameLogEscritorio.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://localhost:443.
        /// </summary>
        public static string ApiGrpcUrl {
            get {
                return ResourceManager.GetString("ApiGrpcUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://localhost/gamelogapi/gamelog/acceso.
        /// </summary>
        public static string ApiUrlAcceso {
            get {
                return ResourceManager.GetString("ApiUrlAcceso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://localhost/gamelogapi/gamelog.
        /// </summary>
        public static string ApiUrlBase {
            get {
                return ResourceManager.GetString("ApiUrlBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://localhost/gamelogapi/gamelog/juego.
        /// </summary>
        public static string ApiUrlJuego {
            get {
                return ResourceManager.GetString("ApiUrlJuego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://localhost/gamelogapi/gamelog/jugador.
        /// </summary>
        public static string ApiUrlJugador {
            get {
                return ResourceManager.GetString("ApiUrlJugador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://localhost/gamelogapi/gamelog/login.
        /// </summary>
        public static string ApiUrlLogin {
            get {
                return ResourceManager.GetString("ApiUrlLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://localhost/gamelogapi/gamelog/MeGusta.
        /// </summary>
        public static string ApiUrlMeGusta {
            get {
                return ResourceManager.GetString("ApiUrlMeGusta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://localhost/gamelogapi/gamelog/notificacion.
        /// </summary>
        public static string ApiURLNotificacion {
            get {
                return ResourceManager.GetString("ApiURLNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://localhost/gamelogapi/gamelog/reporte.
        /// </summary>
        public static string ApiUrlReporte {
            get {
                return ResourceManager.GetString("ApiUrlReporte", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://localhost/gamelogapi/gamelog/resena.
        /// </summary>
        public static string ApiUrlResena {
            get {
                return ResourceManager.GetString("ApiUrlResena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://localhost/gamelogapi/gamelog/seguidor.
        /// </summary>
        public static string ApiUrlSeguidor {
            get {
                return ResourceManager.GetString("ApiUrlSeguidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo que desea ingresar no es una imagen.
        /// </summary>
        public static string ArchivoNoEsImagen {
            get {
                return ResourceManager.GetString("ArchivoNoEsImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Argumentos para realizar la solicitud inválidos.
        /// </summary>
        public static string ArgumentNullExcepcion {
            get {
                return ResourceManager.GetString("ArgumentNullExcepcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se pudo establecer comunicación con el servidor. Por favor, inténtelo más tarde..
        /// </summary>
        public static string BadGetAwayMensaje {
            get {
                return ResourceManager.GetString("BadGetAwayMensaje", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Bienvenido .
        /// </summary>
        public static string Bienvenido {
            get {
                return ResourceManager.GetString("Bienvenido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a System.Net.Http.SocketsHttpHandler.Http2UnencryptedSupport.
        /// </summary>
        public static string ConfiguracionCanalGRPC {
            get {
                return ResourceManager.GetString("ConfiguracionCanalGRPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de poner en lista negra al usuario seleccionado?.
        /// </summary>
        public static string ConfirmacionBanearUsuario {
            get {
                return ResourceManager.GetString("ConfirmacionBanearUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de querer eliminar la reseña seleccionada?.
        /// </summary>
        public static string ConfirmacionEliminacionReseña {
            get {
                return ResourceManager.GetString("ConfirmacionEliminacionReseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de eliminar al jugador seleccionado de su lista de seguidos?.
        /// </summary>
        public static string ConfirmaciónEliminacionSeguido {
            get {
                return ResourceManager.GetString("ConfirmaciónEliminacionSeguido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro de querer eliminar de seguidor al usuario seleccionado?.
        /// </summary>
        public static string ConfirmacionEliminarSeguidor {
            get {
                return ResourceManager.GetString("ConfirmacionEliminarSeguidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 1fc8c6eda3f833495afb4df53a8fe8d20d0519c8d6d81da605c23c5beca5976801e80333065a31aa05445201fc12456662c2937efb00ebbe2cbd63245fb02956cb686ed5f2331b57c4c2a137c53ff85beb107412f8b370e44cfbaae51e2be23e9c2dd9569cbfaa189f4a26668f9e0d48da3b38e50f09180ec7a9fb9385ed2b086c1db3544985b12905db2f629554e853cad4a02b4694024d66697d90eb3017c8cc1f749104a82d153d05f494e51e636416b64f307a3713dbb29fe29c092f0e858c7ff8435872877b6c15599c5548bc7ba9645cc846544daf89e91d53fafb0ebd4f9610d4d31fd459bd39056193e6723fb2bb0eaa07f633d26b8a8cad489a67e4.
        /// </summary>
        public static string ContrasenaServicioNotificacion {
            get {
                return ResourceManager.GetString("ContrasenaServicioNotificacion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo reporte seleccionado muestra los juegos retro, los cuales fueron publicados antes de los años 2000, y que fueron los más reseñados por la comunidad, formando parte de las tendencias revival retro dentro de las fechas seleccionadas..
        /// </summary>
        public static string DescripcionRevivalRetro {
            get {
                return ResourceManager.GetString("DescripcionRevivalRetro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El tipo reporte seleccionado muestra los juegos más reseñados en la por la comunidad, sin importar el tipo de juego o fecha en que fueron publicados. Estos juegos forman parte de las tendencias en las fechas seleccionadas..
        /// </summary>
        public static string DescripcionTendencias {
            get {
                return ResourceManager.GetString("DescripcionTendencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Si desea realizar una modificación, por favor actualice uno de los campos mostrados.
        /// </summary>
        public static string EdicionSinCambios {
            get {
                return ResourceManager.GetString("EdicionSinCambios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El juego a buscar no se encuentra registrado..
        /// </summary>
        public static string ErrorAlBuscarJuego {
            get {
                return ResourceManager.GetString("ErrorAlBuscarJuego", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error al querer leer la imagen a ingresar.
        /// </summary>
        public static string ErrorAlLeerImagen {
            get {
                return ResourceManager.GetString("ErrorAlLeerImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error en la conexion al servidor al intentar obtener los datos de perfil del usuario..
        /// </summary>
        public static string ErrorEnLaCargaDatosUsuario {
            get {
                return ResourceManager.GetString("ErrorEnLaCargaDatosUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a desuscribir_interaccion_resenas.
        /// </summary>
        public static string EventoDesuscribirInteraccionResena {
            get {
                return ResourceManager.GetString("EventoDesuscribirInteraccionResena", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a desuscribir_notificacion_jugador.
        /// </summary>
        public static string EventoDesuscribirNotificacionJugador {
            get {
                return ResourceManager.GetString("EventoDesuscribirNotificacionJugador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a broadcast_mensajes_servidor.
        /// </summary>
        public static string EventoMensajesServidor {
            get {
                return ResourceManager.GetString("EventoMensajesServidor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a notificacion_jugador.
        /// </summary>
        public static string EventoNotificacionJugador {
            get {
                return ResourceManager.GetString("EventoNotificacionJugador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a actualizacion_resenas.
        /// </summary>
        public static string EventoNotificacionResenas {
            get {
                return ResourceManager.GetString("EventoNotificacionResenas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a suscribir_interaccion_resenas.
        /// </summary>
        public static string EventoSuscribirInteraccionReseña {
            get {
                return ResourceManager.GetString("EventoSuscribirInteraccionReseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a suscribir_notificacion_jugador.
        /// </summary>
        public static string EventoSuscribirNotificacionJugador {
            get {
                return ResourceManager.GetString("EventoSuscribirNotificacionJugador", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error inesperado al querer realizar la solicitud.
        /// </summary>
        public static string Excepcion {
            get {
                return ResourceManager.GetString("Excepcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al intentar comunicarse con el servidor de notificaciones. De momento no es posible recibir actualizaciones en tiempo real..
        /// </summary>
        public static string ExcepcionSockets {
            get {
                return ResourceManager.GetString("ExcepcionSockets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fechas inválidas. Por favor verifique de que las fechas sean correctas y que la fecha de inicio de búsqueda no sea mayor a la fecha fin de búsqueda..
        /// </summary>
        public static string FechasInvalidas {
            get {
                return ResourceManager.GetString("FechasInvalidas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Los argumentos para realizar la solicitud no son los correctos, por favor verifique los datos que desea mandar..
        /// </summary>
        public static string GRPCArgumentosInvalidos {
            get {
                return ResourceManager.GetString("GRPCArgumentosInvalidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error al querer ejecutar la operación dentro del servidor multimedia.
        /// </summary>
        public static string GRPCErrorInterno {
            get {
                return ResourceManager.GetString("GRPCErrorInterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No fue posible establecer contacto con el servidor multimedia. Los archivos multimedia mostrados son predeterminados..
        /// </summary>
        public static string GRPCExcepcion {
            get {
                return ResourceManager.GetString("GRPCExcepcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No cuenta con permisos para poder conectarse con el servidor multimedia. .
        /// </summary>
        public static string GRPCPermisosInvalidos {
            get {
                return ResourceManager.GetString("GRPCPermisosInvalidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Actualmente no es posible comunicarse con el servidor para obtener archivos multimedia, se mostrarán imagenes predeterminadas..
        /// </summary>
        public static string GRPCServidorNoDisponible {
            get {
                return ResourceManager.GetString("GRPCServidorNoDisponible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La(s) foto(s) de perfil a obtener no han sido encontradas..
        /// </summary>
        public static string GRPElementosNoEncontrado {
            get {
                return ResourceManager.GetString("GRPElementosNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error en la conexión de internet al intentar realizar la solicitud con el servidor. Verifique su conexión y vuelva a iniciar sesión..
        /// </summary>
        public static string HttpExcepcion {
            get {
                return ResourceManager.GetString("HttpExcepcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La imagen de perfil no fue encontrada..
        /// </summary>
        public static string ImagenNoEncontrada {
            get {
                return ResourceManager.GetString("ImagenNoEncontrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al procesar la respuesta obtenida por el servidor.
        /// </summary>
        public static string JsonExcepcion {
            get {
                return ResourceManager.GetString("JsonExcepcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El juego a buscar no se encuentra registrado..
        /// </summary>
        public static string juegoIngresadoNoEncontrado {
            get {
                return ResourceManager.GetString("juegoIngresadoNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugadores que me siguen.
        /// </summary>
        public static string JugadoresSeguidores {
            get {
                return ResourceManager.GetString("JugadoresSeguidores", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugadores que sigo.
        /// </summary>
        public static string JugadoresSeguidos {
            get {
                return ResourceManager.GetString("JugadoresSeguidos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ventana reseñas de .
        /// </summary>
        public static string NombreVentanaReseña {
            get {
                return ResourceManager.GetString("NombreVentanaReseña", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /gamelognotificaciones/socket.io.
        /// </summary>
        public static string PathNotificaciones {
            get {
                return ResourceManager.GetString("PathNotificaciones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a https://api.rawg.io/api/games/.
        /// </summary>
        public static string RawAPIGames {
            get {
                return ResourceManager.GetString("RawAPIGames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a 531c5bdb92ae41bd819b9901e3012568.
        /// </summary>
        public static string RawgKey {
            get {
                return ResourceManager.GetString("RawgKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Juego no encontrado, quizá quisiste buscar: .
        /// </summary>
        public static string RedireccionamientoSlug {
            get {
                return ResourceManager.GetString("RedireccionamientoSlug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reseñas globales.
        /// </summary>
        public static string ReseñasGlobales {
            get {
                return ResourceManager.GetString("ReseñasGlobales", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reseñas jugadores seguidos.
        /// </summary>
        public static string ReseñasSeguido {
            get {
                return ResourceManager.GetString("ReseñasSeguido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a /home/app/fotos/imagendeperfildefaultgamelog.png.
        /// </summary>
        public static string RutaFotoPorDefecto {
            get {
                return ResourceManager.GetString("RutaFotoPorDefecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El seguidor ha sido eliminado de manera exitosa..
        /// </summary>
        public static string SeguidorEliminado {
            get {
                return ResourceManager.GetString("SeguidorEliminado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a No se ha podido localizar el servidor de archivos multimedia..
        /// </summary>
        public static string ServidorGRPCNoEncontrado {
            get {
                return ResourceManager.GetString("ServidorGRPCNoEncontrado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ha ocurrido un error al conectarse con el servidor de notificaciones. De momento no es posible recibir actualizaciones y notificaciones en tiempo real..
        /// </summary>
        public static string SocketExcepcion {
            get {
                return ResourceManager.GetString("SocketExcepcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a http://localhost:80.
        /// </summary>
        public static string SocketURL {
            get {
                return ResourceManager.GetString("SocketURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El archivo de la imagen a ingresar debe ser menor a 2mb.
        /// </summary>
        public static string TamañoImagenMayor {
            get {
                return ResourceManager.GetString("TamañoImagenMayor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo de espera agotado..
        /// </summary>
        public static string TaskCanceledExcepcion {
            get {
                return ResourceManager.GetString("TaskCanceledExcepcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jugador.
        /// </summary>
        public static string tipoDeUsuarioPorDefecto {
            get {
                return ResourceManager.GetString("tipoDeUsuarioPorDefecto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error al realizar la operacion.
        /// </summary>
        public static string TituloExcepcion {
            get {
                return ResourceManager.GetString("TituloExcepcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Error de conexión .
        /// </summary>
        public static string TituloSocketExcepcion {
            get {
                return ResourceManager.GetString("TituloSocketExcepcion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CMOLogGameUMVX2683.
        /// </summary>
        public static string UsuarioServicioNotificacion {
            get {
                return ResourceManager.GetString("UsuarioServicioNotificacion", resourceCulture);
            }
        }
    }
}
